name: kisan_alert_client
description: Offline-first Mobile Client for Kisan Alert Ingestion & Communications

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  http: ^1.2.0
  uuid: ^4.3.3
  geolocator: ^11.0.0
  provider: ^6.1.1
  flutter_sound: ^9.3.11
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
